version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Initializing environment...
      - echo Logging in to CodeArtifact...
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
          --domain ajay-devops \
          --domain-owner 154993632574 \
          --region ap-south-1 \
          --query authorizationToken \
          --output text)
      - npm config set //ajay-devops-154993632574.d.codeartifact.ap-south-1.amazonaws.com/npm/express-aws/:_authToken=$CODEARTIFACT_AUTH_TOKEN
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - echo Build completed on `date`
  post_build:
    commands:
      - echo Build successful!

artifacts:
  files:
    - index.js
    - package*.json
    - dist/** 
  discard-paths: no
